function prf = probeAbsorptionBS(probe, p, r, z, t)
    % 
    % =====================================================================
    % INPUT:
    %        probe - laser type object representing the probe beam
    %        p - FCC distribution after the pump and diffusion, Nr x Nz x Nt
    %        t - time vector
    %        r - radial spacial coordinate vector [m] 
    %        z - vertical spacial coordinate vector coordiante [m]
    % OUTPUT:
    %        prf - probe intensity spacial distribution after passing
    %              through the sample
    % *********************************************************************
    
    sp = systemParameters();

    Nr = length(r);
    Nz = length(z);
    Nt = length(t);

    dz = z(2)-z(1);

    % Final probe profile matrix:
    prf = zeros(Nr,Nz,Nt);
    
    % Δα matrix:
    dalpha = zeros(Nr,Nz,Nt);
    
    Itemp = zeros(Nr,Nz);

    for it = 1:Nt
        Itemp(:,1) = abs(probe.profile(:,1)).^2;

        for iz = 2:Nz
            % At any time, ΔNe,ΔNh=p (up to matching units), since the
            % FCC concentration is determined by the FCC distribution
            % generated by the pump beam and each photon creates both 1
            % hole and 1 electron
               
            % Calculating the change in indexes at each point
            [~,dalpha(:,iz,it)] = BennetSoref(p(:,iz,it), p(:,iz,it), probe.lambda);
            
            
            % Absorption:
            Itemp(:,iz) = Itemp(:,iz-1) .* exp(-dalpha(:,iz,it)*dz);    % SMALLLLLLLLLLLLLLLL
            
        end
        dalpha1 = dalpha(:,:,1);
        % Calculating the probe spacial profile for each time. Each time
        % represesnts the difference between the time each beam, pump and
        % probe, hit the sample.
        prf(:,:,it) = Itemp(:,:);

    end
end